# frontend/Dockerfile.dev
FROM node:22-slim

WORKDIR /app

COPY package*.json ./

# Add these lines to ensure a clean install
RUN npm install --no-cache && \
    npm cache clean --force
COPY . .

EXPOSE 3000
# If you have a build step for production, it would go here.
# For dev, we just need to start the dev server.
CMD ["npm", "run", "dev"]